/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	danielfoehrkncomv1 "github.com/danielfoehrkn/custom-database-controller/pkg/apis/danielfoehrkn.com/v1"
	autoscalingv1 "k8s.io/api/autoscaling/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTaggers implements TaggerInterface
type FakeTaggers struct {
	Fake *FakeDanielfoehrknV1
	ns   string
}

var taggersResource = schema.GroupVersionResource{Group: "danielfoehrkn.com", Version: "v1", Resource: "taggers"}

var taggersKind = schema.GroupVersionKind{Group: "danielfoehrkn.com", Version: "v1", Kind: "Tagger"}

// Get takes name of the tagger, and returns the corresponding tagger object, and an error if there is any.
func (c *FakeTaggers) Get(name string, options v1.GetOptions) (result *danielfoehrkncomv1.Tagger, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(taggersResource, c.ns, name), &danielfoehrkncomv1.Tagger{})

	if obj == nil {
		return nil, err
	}
	return obj.(*danielfoehrkncomv1.Tagger), err
}

// List takes label and field selectors, and returns the list of Taggers that match those selectors.
func (c *FakeTaggers) List(opts v1.ListOptions) (result *danielfoehrkncomv1.TaggerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(taggersResource, taggersKind, c.ns, opts), &danielfoehrkncomv1.TaggerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &danielfoehrkncomv1.TaggerList{ListMeta: obj.(*danielfoehrkncomv1.TaggerList).ListMeta}
	for _, item := range obj.(*danielfoehrkncomv1.TaggerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested taggers.
func (c *FakeTaggers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(taggersResource, c.ns, opts))

}

// Create takes the representation of a tagger and creates it.  Returns the server's representation of the tagger, and an error, if there is any.
func (c *FakeTaggers) Create(tagger *danielfoehrkncomv1.Tagger) (result *danielfoehrkncomv1.Tagger, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(taggersResource, c.ns, tagger), &danielfoehrkncomv1.Tagger{})

	if obj == nil {
		return nil, err
	}
	return obj.(*danielfoehrkncomv1.Tagger), err
}

// Update takes the representation of a tagger and updates it. Returns the server's representation of the tagger, and an error, if there is any.
func (c *FakeTaggers) Update(tagger *danielfoehrkncomv1.Tagger) (result *danielfoehrkncomv1.Tagger, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(taggersResource, c.ns, tagger), &danielfoehrkncomv1.Tagger{})

	if obj == nil {
		return nil, err
	}
	return obj.(*danielfoehrkncomv1.Tagger), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTaggers) UpdateStatus(tagger *danielfoehrkncomv1.Tagger) (*danielfoehrkncomv1.Tagger, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(taggersResource, "status", c.ns, tagger), &danielfoehrkncomv1.Tagger{})

	if obj == nil {
		return nil, err
	}
	return obj.(*danielfoehrkncomv1.Tagger), err
}

// Delete takes name of the tagger and deletes it. Returns an error if one occurs.
func (c *FakeTaggers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(taggersResource, c.ns, name), &danielfoehrkncomv1.Tagger{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTaggers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(taggersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &danielfoehrkncomv1.TaggerList{})
	return err
}

// Patch applies the patch and returns the patched tagger.
func (c *FakeTaggers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *danielfoehrkncomv1.Tagger, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(taggersResource, c.ns, name, data, subresources...), &danielfoehrkncomv1.Tagger{})

	if obj == nil {
		return nil, err
	}
	return obj.(*danielfoehrkncomv1.Tagger), err
}

// GetScale takes name of the tagger, and returns the corresponding scale object, and an error if there is any.
func (c *FakeTaggers) GetScale(taggerName string, options v1.GetOptions) (result *autoscalingv1.Scale, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetSubresourceAction(taggersResource, c.ns, "scale", taggerName), &autoscalingv1.Scale{})

	if obj == nil {
		return nil, err
	}
	return obj.(*autoscalingv1.Scale), err
}

// UpdateScale takes the representation of a scale and updates it. Returns the server's representation of the scale, and an error, if there is any.
func (c *FakeTaggers) UpdateScale(taggerName string, scale *autoscalingv1.Scale) (result *autoscalingv1.Scale, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(taggersResource, "scale", c.ns, scale), &autoscalingv1.Scale{})

	if obj == nil {
		return nil, err
	}
	return obj.(*autoscalingv1.Scale), err
}
